// File generated by flutterfire_cli.
// For more information, please see https://github.com/firebase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOoZJE1e4T7VmWFz0e4X5R6L5V8M0N0P0',
    appId: '1:123456789:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'fyp-urdu-punjabi-tutor',
    authDomain: 'fyp-urdu-punjabi-tutor.firebaseapp.com',
    storageBucket: 'fyp-urdu-punjabi-tutor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGkR0H9MxTeiEgUBGbnYpsinp5035JKVs',
    appId: '1:512702510637:android:ea829984f70c0ee8142aa4',
    messagingSenderId: '512702510637',
    projectId: 'fyp-urdu-punjabi-tutor',
    storageBucket: 'fyp-urdu-punjabi-tutor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOoZJE1e4T7VmWFz0e4X5R6L5V8M0N0P0',
    appId: '1:123456789:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'fyp-urdu-punjabi-tutor',
    storageBucket: 'fyp-urdu-punjabi-tutor.appspot.com',
    iosBundleId: 'com.example.fypV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOoZJE1e4T7VmWFz0e4X5R6L5V8M0N0P0',
    appId: '1:123456789:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'fyp-urdu-punjabi-tutor',
    storageBucket: 'fyp-urdu-punjabi-tutor.appspot.com',
    iosBundleId: 'com.example.fypV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOoZJE1e4T7VmWFz0e4X5R6L5V8M0N0P0',
    appId: '1:123456789:windows:abcdef1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'fyp-urdu-punjabi-tutor',
    storageBucket: 'fyp-urdu-punjabi-tutor.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDOoZJE1e4T7VmWFz0e4X5R6L5V8M0N0P0',
    appId: '1:123456789:linux:abcdef1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'fyp-urdu-punjabi-tutor',
    storageBucket: 'fyp-urdu-punjabi-tutor.appspot.com',
  );
}
